#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : pypi-expandvars
Version  : 0.8.0
Release  : 3
URL      : https://files.pythonhosted.org/packages/3f/95/e334f9a24445f5fb0467842b1dcdd0e3b2f7393206fd517313f157358c1b/expandvars-0.8.0.tar.gz
Source0  : https://files.pythonhosted.org/packages/3f/95/e334f9a24445f5fb0467842b1dcdd0e3b2f7393206fd517313f157358c1b/expandvars-0.8.0.tar.gz
Summary  : Expand system variables Unix style
Group    : Development/Tools
License  : MIT
Requires: pypi-expandvars-license = %{version}-%{release}
Requires: pypi-expandvars-python = %{version}-%{release}
Requires: pypi-expandvars-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3

%description
expandvars
==========
Expand system variables Unix style
[![PyPI version](https://img.shields.io/pypi/v/expandvars.svg)](https://pypi.org/project/expandvars)
[![codecov](https://codecov.io/gh/sayanarijit/expandvars/branch/master/graph/badge.svg)](https://codecov.io/gh/sayanarijit/expandvars)

%package license
Summary: license components for the pypi-expandvars package.
Group: Default

%description license
license components for the pypi-expandvars package.


%package python
Summary: python components for the pypi-expandvars package.
Group: Default
Requires: pypi-expandvars-python3 = %{version}-%{release}

%description python
python components for the pypi-expandvars package.


%package python3
Summary: python3 components for the pypi-expandvars package.
Group: Default
Requires: python3-core
Provides: pypi(expandvars)

%description python3
python3 components for the pypi-expandvars package.


%prep
%setup -q -n expandvars-0.8.0
cd %{_builddir}/expandvars-0.8.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1646592400
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=auto "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=auto "
export MAKEFLAGS=%{?_smp_mflags}
python3 -m build --wheel --skip-dependency-check --no-isolation

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/pypi-expandvars
cp %{_builddir}/expandvars-0.8.0/LICENSE %{buildroot}/usr/share/package-licenses/pypi-expandvars/c491e1159bef889a43709c1f06d44cef1cb92de4
pip install --root=%{buildroot} --no-deps --ignore-installed dist/*.whl
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/pypi-expandvars/c491e1159bef889a43709c1f06d44cef1cb92de4

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
